name: Unit Test Validation Workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Analysing the code with Pytest
              run: |
                ptest --cov-report=term-missing --cov=src/waddles_cli test/
